name: CI Pipeline

on: [push, pull_request]

jobs:
    lint_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest black pylint
                  pip install -r requirements.txt
            - name: Lint only 4_RagPractice
              run: |
                  flake8 ./4_RagPractice/ --count --select=E9,F63,F7,F82 --show-source --statistics
                  flake8 ./4_RagPractice/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
